on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: xt0rted/markdownlint-problem-matcher@v3
      - run: markdownlint **/*.md
